# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CraflandMap_info.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)
 
_sym_db = _symbol_database.Default()
 



DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x43raflandMap_info.proto\"\x1c\n\nMapRequest\x12\x0e\n\x02uid\x18\x01 \x01(\tR\x02uid\"L\n\x07MapInfo\x12\x17\n\x07MapCode\x18\x01 \x01(\tR\x07MapCode\x12\x19\n\x08MapTitle\x18\x02 \x01(\tR\x08MapTitle\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription2P\n\x13\x43raftlandMapService\x12\x39\n\nGetMapInfo\x12\x0f.MapRequest\x1a\x08.MapInfo\"\x10\x62\x06proto3')
 
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CraflandMap_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:;   
  DESCRIPTOR._options = None;   
  _globals['_MAPREQUEST']._serialized_start=27
  _globals['_MAPREQUEST']._serialized_end=55;
  _globals['_MAPINFO']._serialized_start=57;   
  _globals['_MAPINFO']._serialized_end=133
  _globals['_CRAFTLANDMAPSERVICE']._serialized_start=135
  _globals['_CRAFTLANDMAPSERVICE']._serialized_end=215
# @@protoc_insertion_point(module_scope)
  