# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prime_level.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'prime_level.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11prime_level.proto\x12\x08\x66reefire\"*\n\x05Users\x12!\n\tbasicinfo\x18\x01 \x03(\x0b\x32\x0e.freefire.info\"\x1c\n\x05prime\x12\x13\n\x0bprime_level\x18\x02 \x01(\r\">\n\x04info\x12\x10\n\x08username\x18\x03 \x01(\t\x12$\n\x0bprime_level\x18L \x01(\x0b\x32\x0f.freefire.primeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prime_level_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERS']._serialized_start=31
  _globals['_USERS']._serialized_end=73
  _globals['_PRIME']._serialized_start=75
  _globals['_PRIME']._serialized_end=103
  _globals['_INFO']._serialized_start=105
  _globals['_INFO']._serialized_end=167
# @@protoc_insertion_point(module_scope)
